name = 'jmdev'
description = 'Theme for JesusMarin.Dev'

# Taxonomy terms
tags = ['blog', 'web']
features = ['hugo', 'html', 'css']

# If the theme has a single author
[author]
  name = 'Jesus Marin'
  homepage = 'https://jesusmarin.dev'
