# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 691a54d800d8f007820712303b9860acb68e41b017e6743e4717a9335bb75c487be3d257934dd26fb582a452e46eac715f14499266968e00ae64fd768324682d

test:
  secret_key_base: 89e12fce2faab7d35705bd030c8cd4cda22adc8fd28f2e0ff67b82402cd1ae16951fb9fea6e42528c93014d98cd773f8dcaeade91535915847d0289a0e6b90ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
