name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Build and publish the Docker image
      run: |
        docker login --username jesusangelm --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/jesusangelm/blog:latest
        docker push ghcr.io/jesusangelm/blog:latest
