name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        if: github.event_name == 'pull_request'
        run: docker build . --file Dockerfile --tag ghcr.io/jesusangelm/blog:latest

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u jesusangelm --password-stdin

      - name: Build and publish the Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build . --file Dockerfile --tag ghcr.io/jesusangelm:latest
          docker push ghcr.io/jesusangelm/blog:latest